apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ComponentD
  description: Component main website
spec:
  type: website
  lifecycle: production
  owner: team-a
  system: ComponentD-engagement-portal
