apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: serviceC
  description: Component main service
spec:
  type: service
  lifecycle: production
  owner: team-a
  system: ComponentD-engagement-portal
