apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: serviceB
  description: ServiceB Test
spec:
  type: service
  lifecycle: production
  owner: team-a
  system: ServiceB-engagement-portal
